package(default_visibility = ["//base:__subpackages__"])

filegroup(
    name = "headers",
    srcs = [
        "json_file_value_serializer.h",
        "json_parser.h",
        "json_reader.h",
        "json_string_value_serializer.h",
        "json_value_converter.h",
        "json_writer.h",
        "string_escape.h",
    ],
)

filegroup(
    name = "json",
    srcs = [
        "json_file_value_serializer.cc",
        "json_parser.cc",
        "json_reader.cc",
        "json_string_value_serializer.cc",
        "json_value_converter.cc",
        "json_writer.cc",
        "string_escape.cc",
    ],
)

filegroup(
    name = "unit_test",
    srcs = [
        "json_parser_unittest.cc",
        "json_reader_unittest.cc",
        "json_value_converter_unittest.cc",
        "json_value_serializer_unittest.cc",
        "json_writer_unittest.cc",
        "string_escape_unittest.cc",
    ],
)
