package(default_visibility = ["//base:__subpackages__"])

filegroup(
    name = "headers",
    srcs = [
        "checked_math.h",
        "clamped_math.h",
        "math_constants.h",
        "ranges.h",
        "safe_conversions.h",
        "safe_math.h",
    ],
)

filegroup(
    name = "numerics",
    srcs = [
        "checked_math_impl.h",
        "clamped_math_impl.h",
        "safe_conversions_arm_impl.h",
        "safe_conversions_impl.h",
        "safe_math_arm_impl.h",
        "safe_math_clang_gcc_impl.h",
        "safe_math_shared_impl.h",
    ],
)
