package(default_visibility = ["//base:__subpackages__"])

filegroup(
    name = "containers",
    srcs = [
        "adapters.h",
        "checked_iterators.h",
        "circular_deque.h",
        "flat_map.h",
        "flat_set.h",
        "flat_tree.h",
        "hash_tables.h",
        "id_map.h",
        "linked_list.h",
        "mru_cache.h",
        "queue.h",
        "small_map.h",
        "span.h",
        "stack.h",
        "stack_container.h",
        "unique_ptr_adapters.h",
        "vector_buffer.h",
    ],
)

filegroup(
    name = "unit_test",
    srcs = [
        "adapters_unittest.cc",
        "circular_deque_unittest.cc",
        "flat_map_unittest.cc",
        "flat_set_unittest.cc",
        "flat_tree_unittest.cc",
        "hash_tables_unittest.cc",
        "id_map_unittest.cc",
        "linked_list_unittest.cc",
        "mru_cache_unittest.cc",
        "small_map_unittest.cc",
        "span_unittest.cc",
        "stack_container_unittest.cc",
        "unique_ptr_adapters_unittest.cc",
        "vector_buffer_unittest.cc",
    ],
)
