package(default_visibility = ["//base:__subpackages__"])

filegroup(
    name = "headers",
    srcs = [
        "system_monitor.h",
    ],
)

filegroup(
    name = "system",
    srcs = [
        "system_monitor.cc",
    ],
)

filegroup(
    name = "unit_test",
    srcs = [
        "system_monitor_unittest.cc",
    ],
)
