package(default_visibility = ["//base:__subpackages__"])

filegroup(
    name = "headers",
    srcs = [
        "power_monitor.h",
        "power_monitor_device_source.h",
        "power_monitor_source.h",
        "power_observer.h",
    ],
)

filegroup(
    name = "power_monitor",
    srcs = [
        "power_monitor.cc",
        "power_monitor_device_source.cc",
        "power_monitor_device_source_stub.cc",
        "power_monitor_source.cc",
    ],
)

filegroup(
    name = "unit_test",
    srcs = [
        "power_monitor_unittest.cc",
    ],
)
