package(default_visibility = ["//base:__subpackages__"])

filegroup(
    name = "headers",
    srcs = [
        "mime_util_xdg.h",
        "xdg_util.h",
    ],
)

filegroup(
    name = "nix",
    srcs = [
        "mime_util_xdg.cc",
        "xdg_util.cc",
    ],
)
